envVarGroups:
  - name: shared-config
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET_NAME
        sync: false

services:
  - type: web
    name: ipo-backend
    env: docker
    dockerContext: backend
    dockerfilePath: Dockerfile
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: ipo-redis
          property: connectionString
      - key: PDF_PARSER_URL
        value: "http://ipo-pdf-parser:8000"
      - fromGroup: shared-config



  - type: web
    name: ipo-pdf-parser
    env: docker
    dockerContext: pdf-parser
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - fromGroup: shared-config

  - type: redis
    name: ipo-redis
    plan: free
    ipAllowList: []
