// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_analysis.sql

package models

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const countIPOsWithAIAnalysis = `-- name: CountIPOsWithAIAnalysis :one
SELECT COUNT(*) FROM ai_analysis WHERE red_flags IS NOT NULL
`

func (q *Queries) CountIPOsWithAIAnalysis(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIPOsWithAIAnalysis)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countParsedIPOs = `-- name: CountParsedIPOs :one
SELECT COUNT(*) FROM ai_analysis WHERE raw_json IS NOT NULL
`

func (q *Queries) CountParsedIPOs(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countParsedIPOs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrUpdateAIAnalysis = `-- name: CreateOrUpdateAIAnalysis :one
INSERT INTO ai_analysis (
    ipo_id,
    business_model,
    moat,
    promoter_risk,
    legal_cases,
    customer_concentration,
    debt_assessment,
    key_risks,
    red_flags,
    management_assumptions,
    industry_outlook,
    raw_json
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
ON CONFLICT (ipo_id) DO UPDATE SET
    business_model = EXCLUDED.business_model,
    moat = EXCLUDED.moat,
    promoter_risk = EXCLUDED.promoter_risk,
    legal_cases = EXCLUDED.legal_cases,
    customer_concentration = EXCLUDED.customer_concentration,
    debt_assessment = EXCLUDED.debt_assessment,
    key_risks = EXCLUDED.key_risks,
    red_flags = EXCLUDED.red_flags,
    management_assumptions = EXCLUDED.management_assumptions,
    industry_outlook = EXCLUDED.industry_outlook,
    raw_json = EXCLUDED.raw_json
RETURNING id, ipo_id, business_model, moat, promoter_risk, legal_cases, customer_concentration, debt_assessment, key_risks, red_flags, management_assumptions, industry_outlook, raw_json
`

type CreateOrUpdateAIAnalysisParams struct {
	IpoID                 int64
	BusinessModel         sql.NullString
	Moat                  sql.NullString
	PromoterRisk          sql.NullString
	LegalCases            sql.NullString
	CustomerConcentration sql.NullString
	DebtAssessment        sql.NullString
	KeyRisks              sql.NullString
	RedFlags              sql.NullString
	ManagementAssumptions sql.NullString
	IndustryOutlook       sql.NullString
	RawJson               pqtype.NullRawMessage
}

func (q *Queries) CreateOrUpdateAIAnalysis(ctx context.Context, arg CreateOrUpdateAIAnalysisParams) (AiAnalysis, error) {
	row := q.db.QueryRowContext(ctx, createOrUpdateAIAnalysis,
		arg.IpoID,
		arg.BusinessModel,
		arg.Moat,
		arg.PromoterRisk,
		arg.LegalCases,
		arg.CustomerConcentration,
		arg.DebtAssessment,
		arg.KeyRisks,
		arg.RedFlags,
		arg.ManagementAssumptions,
		arg.IndustryOutlook,
		arg.RawJson,
	)
	var i AiAnalysis
	err := row.Scan(
		&i.ID,
		&i.IpoID,
		&i.BusinessModel,
		&i.Moat,
		&i.PromoterRisk,
		&i.LegalCases,
		&i.CustomerConcentration,
		&i.DebtAssessment,
		&i.KeyRisks,
		&i.RedFlags,
		&i.ManagementAssumptions,
		&i.IndustryOutlook,
		&i.RawJson,
	)
	return i, err
}

const getAIAnalysisByIPO = `-- name: GetAIAnalysisByIPO :one
SELECT id, ipo_id, business_model, moat, promoter_risk, legal_cases, customer_concentration, debt_assessment, key_risks, red_flags, management_assumptions, industry_outlook, raw_json FROM ai_analysis
WHERE ipo_id = $1
`

func (q *Queries) GetAIAnalysisByIPO(ctx context.Context, ipoID int64) (AiAnalysis, error) {
	row := q.db.QueryRowContext(ctx, getAIAnalysisByIPO, ipoID)
	var i AiAnalysis
	err := row.Scan(
		&i.ID,
		&i.IpoID,
		&i.BusinessModel,
		&i.Moat,
		&i.PromoterRisk,
		&i.LegalCases,
		&i.CustomerConcentration,
		&i.DebtAssessment,
		&i.KeyRisks,
		&i.RedFlags,
		&i.ManagementAssumptions,
		&i.IndustryOutlook,
		&i.RawJson,
	)
	return i, err
}
