// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package models

import (
	"context"
)

const countRecentGMPTracked = `-- name: CountRecentGMPTracked :one
SELECT COUNT(DISTINCT ipo_id)
FROM gmp_history
WHERE ($1::int = 0 OR recorded_at >= NOW() - ($1::int * INTERVAL '1 hour'))
`

func (q *Queries) CountRecentGMPTracked(ctx context.Context, dollar_1 int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentGMPTracked, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentPeersTracked = `-- name: CountRecentPeersTracked :one
SELECT COUNT(DISTINCT ipo_id)
FROM peer_companies
WHERE ($1::int = 0 OR created_at >= NOW() - ($1::int * INTERVAL '1 hour'))
`

func (q *Queries) CountRecentPeersTracked(ctx context.Context, dollar_1 int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentPeersTracked, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentSubscriptionsTracked = `-- name: CountRecentSubscriptionsTracked :one
SELECT COUNT(DISTINCT ipo_id)
FROM subscription_data
WHERE ($1::int = 0 OR recorded_at >= NOW() - ($1::int * INTERVAL '1 hour'))
`

func (q *Queries) CountRecentSubscriptionsTracked(ctx context.Context, dollar_1 int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentSubscriptionsTracked, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentValuationsTracked = `-- name: CountRecentValuationsTracked :one
SELECT COUNT(DISTINCT ipo_id)
FROM valuation
WHERE ($1::int = 0 OR updated_at >= NOW() - ($1::int * INTERVAL '1 hour'))
`

func (q *Queries) CountRecentValuationsTracked(ctx context.Context, dollar_1 int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentValuationsTracked, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}
