// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package models

import (
	"context"
	"database/sql"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    ipo_id,
    file_path,
    type,
    downloaded_at
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, ipo_id, type, file_path, downloaded_at, parsed_at
`

type CreateDocumentParams struct {
	IpoID        int64
	FilePath     string
	Type         string
	DownloadedAt sql.NullTime
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.IpoID,
		arg.FilePath,
		arg.Type,
		arg.DownloadedAt,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.IpoID,
		&i.Type,
		&i.FilePath,
		&i.DownloadedAt,
		&i.ParsedAt,
	)
	return i, err
}
