// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: financials.sql

package models

import (
	"context"
	"database/sql"
)

const countIPOsWithFinancials = `-- name: CountIPOsWithFinancials :one
SELECT COUNT(DISTINCT ipo_id) FROM financials
`

func (q *Queries) CountIPOsWithFinancials(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIPOsWithFinancials)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrUpdateFinancials = `-- name: CreateOrUpdateFinancials :one
INSERT INTO financials (
    ipo_id,
    year,
    revenue,
    pat,
    ebitda,
    total_assets,
    total_debt,
    equity
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (ipo_id, year) DO UPDATE SET
    revenue = EXCLUDED.revenue,
    pat = EXCLUDED.pat,
    ebitda = EXCLUDED.ebitda,
    total_assets = EXCLUDED.total_assets,
    total_debt = EXCLUDED.total_debt,
    equity = EXCLUDED.equity
RETURNING id, ipo_id, year, revenue, pat, ebitda, total_assets, total_debt, equity
`

type CreateOrUpdateFinancialsParams struct {
	IpoID       int64
	Year        int32
	Revenue     sql.NullString
	Pat         sql.NullString
	Ebitda      sql.NullString
	TotalAssets sql.NullString
	TotalDebt   sql.NullString
	Equity      sql.NullString
}

func (q *Queries) CreateOrUpdateFinancials(ctx context.Context, arg CreateOrUpdateFinancialsParams) (Financial, error) {
	row := q.db.QueryRowContext(ctx, createOrUpdateFinancials,
		arg.IpoID,
		arg.Year,
		arg.Revenue,
		arg.Pat,
		arg.Ebitda,
		arg.TotalAssets,
		arg.TotalDebt,
		arg.Equity,
	)
	var i Financial
	err := row.Scan(
		&i.ID,
		&i.IpoID,
		&i.Year,
		&i.Revenue,
		&i.Pat,
		&i.Ebitda,
		&i.TotalAssets,
		&i.TotalDebt,
		&i.Equity,
	)
	return i, err
}

const getFinancialsByIPO = `-- name: GetFinancialsByIPO :many
SELECT id, ipo_id, year, revenue, pat, ebitda, total_assets, total_debt, equity FROM financials
WHERE ipo_id = $1
ORDER BY year DESC
`

func (q *Queries) GetFinancialsByIPO(ctx context.Context, ipoID int64) ([]Financial, error) {
	rows, err := q.db.QueryContext(ctx, getFinancialsByIPO, ipoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Financial
	for rows.Next() {
		var i Financial
		if err := rows.Scan(
			&i.ID,
			&i.IpoID,
			&i.Year,
			&i.Revenue,
			&i.Pat,
			&i.Ebitda,
			&i.TotalAssets,
			&i.TotalDebt,
			&i.Equity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
