// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gmp.sql

package models

import (
	"context"
	"database/sql"
)

const createGMPHistory = `-- name: CreateGMPHistory :one
INSERT INTO gmp_history (
    ipo_id,
    gmp_amount,
    premium_percent
) VALUES (
    $1, $2, $3
)
RETURNING id, ipo_id, gmp_amount, premium_percent, recorded_at
`

type CreateGMPHistoryParams struct {
	IpoID          int64
	GmpAmount      sql.NullString
	PremiumPercent sql.NullString
}

func (q *Queries) CreateGMPHistory(ctx context.Context, arg CreateGMPHistoryParams) (GmpHistory, error) {
	row := q.db.QueryRowContext(ctx, createGMPHistory, arg.IpoID, arg.GmpAmount, arg.PremiumPercent)
	var i GmpHistory
	err := row.Scan(
		&i.ID,
		&i.IpoID,
		&i.GmpAmount,
		&i.PremiumPercent,
		&i.RecordedAt,
	)
	return i, err
}

const getLatestGMP = `-- name: GetLatestGMP :one
SELECT id, ipo_id, gmp_amount, premium_percent, recorded_at FROM gmp_history
WHERE ipo_id = $1
ORDER BY recorded_at DESC
LIMIT 1
`

func (q *Queries) GetLatestGMP(ctx context.Context, ipoID int64) (GmpHistory, error) {
	row := q.db.QueryRowContext(ctx, getLatestGMP, ipoID)
	var i GmpHistory
	err := row.Scan(
		&i.ID,
		&i.IpoID,
		&i.GmpAmount,
		&i.PremiumPercent,
		&i.RecordedAt,
	)
	return i, err
}
