// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ipos.sql

package models

import (
	"context"
	"database/sql"
)

const createIPO = `-- name: CreateIPO :one
INSERT INTO ipos (
    name,
    exchange_type,
    sector,
    price_band_low,
    price_band_high,
    open_date,
    close_date,
    listing_date,
    status,
    source_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, name, exchange_type, sector, price_band_low, price_band_high, open_date, close_date, listing_date, status, source_url
`

type CreateIPOParams struct {
	Name          string
	ExchangeType  sql.NullString
	Sector        sql.NullString
	PriceBandLow  sql.NullString
	PriceBandHigh sql.NullString
	OpenDate      sql.NullTime
	CloseDate     sql.NullTime
	ListingDate   sql.NullTime
	Status        sql.NullString
	SourceUrl     sql.NullString
}

func (q *Queries) CreateIPO(ctx context.Context, arg CreateIPOParams) (Ipo, error) {
	row := q.db.QueryRowContext(ctx, createIPO,
		arg.Name,
		arg.ExchangeType,
		arg.Sector,
		arg.PriceBandLow,
		arg.PriceBandHigh,
		arg.OpenDate,
		arg.CloseDate,
		arg.ListingDate,
		arg.Status,
		arg.SourceUrl,
	)
	var i Ipo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ExchangeType,
		&i.Sector,
		&i.PriceBandLow,
		&i.PriceBandHigh,
		&i.OpenDate,
		&i.CloseDate,
		&i.ListingDate,
		&i.Status,
		&i.SourceUrl,
	)
	return i, err
}

const getActiveIPOs = `-- name: GetActiveIPOs :many
SELECT id, name, exchange_type, sector, price_band_low, price_band_high, open_date, close_date, listing_date, status, source_url FROM ipos
WHERE status IN ('ACTIVE', 'UPCOMING')
ORDER BY open_date ASC
`

func (q *Queries) GetActiveIPOs(ctx context.Context) ([]Ipo, error) {
	rows, err := q.db.QueryContext(ctx, getActiveIPOs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ipo
	for rows.Next() {
		var i Ipo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ExchangeType,
			&i.Sector,
			&i.PriceBandLow,
			&i.PriceBandHigh,
			&i.OpenDate,
			&i.CloseDate,
			&i.ListingDate,
			&i.Status,
			&i.SourceUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIPO = `-- name: GetIPO :one
SELECT id, name, exchange_type, sector, price_band_low, price_band_high, open_date, close_date, listing_date, status, source_url FROM ipos
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetIPO(ctx context.Context, id int64) (Ipo, error) {
	row := q.db.QueryRowContext(ctx, getIPO, id)
	var i Ipo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ExchangeType,
		&i.Sector,
		&i.PriceBandLow,
		&i.PriceBandHigh,
		&i.OpenDate,
		&i.CloseDate,
		&i.ListingDate,
		&i.Status,
		&i.SourceUrl,
	)
	return i, err
}

const getIPOByName = `-- name: GetIPOByName :one
SELECT id, name, exchange_type, sector, price_band_low, price_band_high, open_date, close_date, listing_date, status, source_url FROM ipos
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetIPOByName(ctx context.Context, name string) (Ipo, error) {
	row := q.db.QueryRowContext(ctx, getIPOByName, name)
	var i Ipo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ExchangeType,
		&i.Sector,
		&i.PriceBandLow,
		&i.PriceBandHigh,
		&i.OpenDate,
		&i.CloseDate,
		&i.ListingDate,
		&i.Status,
		&i.SourceUrl,
	)
	return i, err
}

const listIPOs = `-- name: ListIPOs :many
SELECT id, name, exchange_type, sector, price_band_low, price_band_high, open_date, close_date, listing_date, status, source_url FROM ipos
ORDER BY open_date DESC
LIMIT $1 OFFSET $2
`

type ListIPOsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListIPOs(ctx context.Context, arg ListIPOsParams) ([]Ipo, error) {
	rows, err := q.db.QueryContext(ctx, listIPOs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ipo
	for rows.Next() {
		var i Ipo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ExchangeType,
			&i.Sector,
			&i.PriceBandLow,
			&i.PriceBandHigh,
			&i.OpenDate,
			&i.CloseDate,
			&i.ListingDate,
			&i.Status,
			&i.SourceUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIPO = `-- name: UpdateIPO :one
UPDATE ipos
SET 
    exchange_type = $2,
    open_date = $3,
    close_date = $4,
    status = $5
WHERE id = $1
RETURNING id, name, exchange_type, sector, price_band_low, price_band_high, open_date, close_date, listing_date, status, source_url
`

type UpdateIPOParams struct {
	ID           int64
	ExchangeType sql.NullString
	OpenDate     sql.NullTime
	CloseDate    sql.NullTime
	Status       sql.NullString
}

func (q *Queries) UpdateIPO(ctx context.Context, arg UpdateIPOParams) (Ipo, error) {
	row := q.db.QueryRowContext(ctx, updateIPO,
		arg.ID,
		arg.ExchangeType,
		arg.OpenDate,
		arg.CloseDate,
		arg.Status,
	)
	var i Ipo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ExchangeType,
		&i.Sector,
		&i.PriceBandLow,
		&i.PriceBandHigh,
		&i.OpenDate,
		&i.CloseDate,
		&i.ListingDate,
		&i.Status,
		&i.SourceUrl,
	)
	return i, err
}
