// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

type AiAnalysis struct {
	ID                    int64
	IpoID                 int64
	BusinessModel         sql.NullString
	Moat                  sql.NullString
	PromoterRisk          sql.NullString
	LegalCases            sql.NullString
	CustomerConcentration sql.NullString
	DebtAssessment        sql.NullString
	KeyRisks              sql.NullString
	RedFlags              sql.NullString
	ManagementAssumptions sql.NullString
	IndustryOutlook       sql.NullString
	RawJson               pqtype.NullRawMessage
}

type Document struct {
	ID           int64
	IpoID        int64
	Type         string
	FilePath     string
	DownloadedAt sql.NullTime
	ParsedAt     sql.NullTime
}

type Financial struct {
	ID          int64
	IpoID       int64
	Year        int32
	Revenue     sql.NullString
	Pat         sql.NullString
	Ebitda      sql.NullString
	TotalAssets sql.NullString
	TotalDebt   sql.NullString
	Equity      sql.NullString
}

type GmpHistory struct {
	ID             int64
	IpoID          int64
	GmpAmount      sql.NullString
	PremiumPercent sql.NullString
	RecordedAt     sql.NullTime
}

type Ipo struct {
	ID            int64
	Name          string
	ExchangeType  sql.NullString
	Sector        sql.NullString
	PriceBandLow  sql.NullString
	PriceBandHigh sql.NullString
	OpenDate      sql.NullTime
	CloseDate     sql.NullTime
	ListingDate   sql.NullTime
	Status        sql.NullString
	SourceUrl     sql.NullString
}

type IpoOutcome struct {
	ID                int64
	IpoID             int64
	IssuePrice        sql.NullString
	ListingPrice      sql.NullString
	ListingReturnPct  sql.NullString
	OneMonthReturnPct sql.NullString
	SixMonthReturnPct sql.NullString
	OneYearReturnPct  sql.NullString
	OurScoreAtListing sql.NullString
}

type PeerCompany struct {
	ID        int64
	IpoID     int64
	Name      string
	Ticker    sql.NullString
	Pe        sql.NullString
	Pb        sql.NullString
	EvEbitda  sql.NullString
	Roe       sql.NullString
	MarketCap sql.NullString
}

type Report struct {
	ID          int64
	IpoID       int64
	FilePath    string
	Format      string
	GeneratedAt sql.NullTime
}

type Score struct {
	ID                int64
	IpoID             int64
	FinancialsScore   sql.NullString
	FinancialsReason  sql.NullString
	ValuationScore    sql.NullString
	ValuationReason   sql.NullString
	PromoterScore     sql.NullString
	PromoterReason    sql.NullString
	IndustryScore     sql.NullString
	IndustryReason    sql.NullString
	RiskScore         sql.NullString
	RiskReason        sql.NullString
	SubscriptionScore sql.NullString
	GmpScore          sql.NullString
	FinalScore        sql.NullString
	Recommendation    sql.NullString
	ScoredAt          sql.NullTime
}

type SubscriptionDatum struct {
	ID              int64
	IpoID           int64
	Category        string
	TimesSubscribed sql.NullString
	RecordedAt      sql.NullTime
}

type Valuation struct {
	ID         int64
	IpoID      int64
	IssuePrice sql.NullString
	MarketCap  sql.NullString
	PeRatio    sql.NullString
	PbRatio    sql.NullString
	EvEbitda   sql.NullString
}
