// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: peers.sql

package models

import (
	"context"
	"database/sql"
)

const deletePeerCompaniesByIPO = `-- name: DeletePeerCompaniesByIPO :exec
DELETE FROM peer_companies
WHERE ipo_id = $1
`

func (q *Queries) DeletePeerCompaniesByIPO(ctx context.Context, ipoID int64) error {
	_, err := q.db.ExecContext(ctx, deletePeerCompaniesByIPO, ipoID)
	return err
}

const getPeerCompaniesByIPO = `-- name: GetPeerCompaniesByIPO :many
SELECT id, ipo_id, name, ticker, pe, pb, ev_ebitda, roe, market_cap, created_at FROM peer_companies
WHERE ipo_id = $1
ORDER BY market_cap DESC
`

func (q *Queries) GetPeerCompaniesByIPO(ctx context.Context, ipoID int64) ([]PeerCompany, error) {
	rows, err := q.db.QueryContext(ctx, getPeerCompaniesByIPO, ipoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeerCompany
	for rows.Next() {
		var i PeerCompany
		if err := rows.Scan(
			&i.ID,
			&i.IpoID,
			&i.Name,
			&i.Ticker,
			&i.Pe,
			&i.Pb,
			&i.EvEbitda,
			&i.Roe,
			&i.MarketCap,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPeerCompany = `-- name: InsertPeerCompany :one
INSERT INTO peer_companies (
    ipo_id, name, ticker, pe, pb, ev_ebitda, roe, market_cap
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, ipo_id, name, ticker, pe, pb, ev_ebitda, roe, market_cap, created_at
`

type InsertPeerCompanyParams struct {
	IpoID     int64
	Name      string
	Ticker    sql.NullString
	Pe        sql.NullString
	Pb        sql.NullString
	EvEbitda  sql.NullString
	Roe       sql.NullString
	MarketCap sql.NullString
}

func (q *Queries) InsertPeerCompany(ctx context.Context, arg InsertPeerCompanyParams) (PeerCompany, error) {
	row := q.db.QueryRowContext(ctx, insertPeerCompany,
		arg.IpoID,
		arg.Name,
		arg.Ticker,
		arg.Pe,
		arg.Pb,
		arg.EvEbitda,
		arg.Roe,
		arg.MarketCap,
	)
	var i PeerCompany
	err := row.Scan(
		&i.ID,
		&i.IpoID,
		&i.Name,
		&i.Ticker,
		&i.Pe,
		&i.Pb,
		&i.EvEbitda,
		&i.Roe,
		&i.MarketCap,
		&i.CreatedAt,
	)
	return i, err
}
