// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package models

import (
	"context"
)

const createOrUpdateReport = `-- name: CreateOrUpdateReport :one
INSERT INTO reports (
    ipo_id,
    file_path,
    format
) VALUES (
    $1, $2, $3
)
ON CONFLICT (ipo_id, format) DO UPDATE
SET
    file_path = EXCLUDED.file_path,
    generated_at = CURRENT_TIMESTAMP
RETURNING id, ipo_id, file_path, format, generated_at
`

type CreateOrUpdateReportParams struct {
	IpoID    int64
	FilePath string
	Format   string
}

func (q *Queries) CreateOrUpdateReport(ctx context.Context, arg CreateOrUpdateReportParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, createOrUpdateReport, arg.IpoID, arg.FilePath, arg.Format)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.IpoID,
		&i.FilePath,
		&i.Format,
		&i.GeneratedAt,
	)
	return i, err
}

const getReportByIPO = `-- name: GetReportByIPO :one
SELECT id, ipo_id, file_path, format, generated_at FROM reports
WHERE ipo_id = $1 AND format = $2 LIMIT 1
`

type GetReportByIPOParams struct {
	IpoID  int64
	Format string
}

func (q *Queries) GetReportByIPO(ctx context.Context, arg GetReportByIPOParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, getReportByIPO, arg.IpoID, arg.Format)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.IpoID,
		&i.FilePath,
		&i.Format,
		&i.GeneratedAt,
	)
	return i, err
}
