// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scores.sql

package models

import (
	"context"
	"database/sql"
)

const countIPOsWithScores = `-- name: CountIPOsWithScores :one
SELECT COUNT(DISTINCT ipo_id) FROM scores
`

func (q *Queries) CountIPOsWithScores(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIPOsWithScores)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrUpdateScore = `-- name: CreateOrUpdateScore :one
INSERT INTO scores (
    ipo_id,
    financials_score, financials_reason,
    valuation_score, valuation_reason,
    promoter_score, promoter_reason,
    industry_score, industry_reason,
    risk_score, risk_reason,
    subscription_score,
    gmp_score,
    final_score,
    recommendation,
    scored_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, CURRENT_TIMESTAMP
)
ON CONFLICT (ipo_id) DO UPDATE 
SET financials_score = EXCLUDED.financials_score,
    financials_reason = EXCLUDED.financials_reason,
    valuation_score = EXCLUDED.valuation_score,
    valuation_reason = EXCLUDED.valuation_reason,
    promoter_score = EXCLUDED.promoter_score,
    promoter_reason = EXCLUDED.promoter_reason,
    industry_score = EXCLUDED.industry_score,
    industry_reason = EXCLUDED.industry_reason,
    risk_score = EXCLUDED.risk_score,
    risk_reason = EXCLUDED.risk_reason,
    subscription_score = EXCLUDED.subscription_score,
    gmp_score = EXCLUDED.gmp_score,
    final_score = EXCLUDED.final_score,
    recommendation = EXCLUDED.recommendation,
    scored_at = CURRENT_TIMESTAMP
RETURNING id, ipo_id, financials_score, financials_reason, valuation_score, valuation_reason, promoter_score, promoter_reason, industry_score, industry_reason, risk_score, risk_reason, subscription_score, gmp_score, final_score, recommendation, scored_at
`

type CreateOrUpdateScoreParams struct {
	IpoID             int64
	FinancialsScore   sql.NullString
	FinancialsReason  sql.NullString
	ValuationScore    sql.NullString
	ValuationReason   sql.NullString
	PromoterScore     sql.NullString
	PromoterReason    sql.NullString
	IndustryScore     sql.NullString
	IndustryReason    sql.NullString
	RiskScore         sql.NullString
	RiskReason        sql.NullString
	SubscriptionScore sql.NullString
	GmpScore          sql.NullString
	FinalScore        sql.NullString
	Recommendation    sql.NullString
}

func (q *Queries) CreateOrUpdateScore(ctx context.Context, arg CreateOrUpdateScoreParams) (Score, error) {
	row := q.db.QueryRowContext(ctx, createOrUpdateScore,
		arg.IpoID,
		arg.FinancialsScore,
		arg.FinancialsReason,
		arg.ValuationScore,
		arg.ValuationReason,
		arg.PromoterScore,
		arg.PromoterReason,
		arg.IndustryScore,
		arg.IndustryReason,
		arg.RiskScore,
		arg.RiskReason,
		arg.SubscriptionScore,
		arg.GmpScore,
		arg.FinalScore,
		arg.Recommendation,
	)
	var i Score
	err := row.Scan(
		&i.ID,
		&i.IpoID,
		&i.FinancialsScore,
		&i.FinancialsReason,
		&i.ValuationScore,
		&i.ValuationReason,
		&i.PromoterScore,
		&i.PromoterReason,
		&i.IndustryScore,
		&i.IndustryReason,
		&i.RiskScore,
		&i.RiskReason,
		&i.SubscriptionScore,
		&i.GmpScore,
		&i.FinalScore,
		&i.Recommendation,
		&i.ScoredAt,
	)
	return i, err
}

const getScoreByIPO = `-- name: GetScoreByIPO :one
SELECT id, ipo_id, financials_score, financials_reason, valuation_score, valuation_reason, promoter_score, promoter_reason, industry_score, industry_reason, risk_score, risk_reason, subscription_score, gmp_score, final_score, recommendation, scored_at FROM scores
WHERE ipo_id = $1 LIMIT 1
`

func (q *Queries) GetScoreByIPO(ctx context.Context, ipoID int64) (Score, error) {
	row := q.db.QueryRowContext(ctx, getScoreByIPO, ipoID)
	var i Score
	err := row.Scan(
		&i.ID,
		&i.IpoID,
		&i.FinancialsScore,
		&i.FinancialsReason,
		&i.ValuationScore,
		&i.ValuationReason,
		&i.PromoterScore,
		&i.PromoterReason,
		&i.IndustryScore,
		&i.IndustryReason,
		&i.RiskScore,
		&i.RiskReason,
		&i.SubscriptionScore,
		&i.GmpScore,
		&i.FinalScore,
		&i.Recommendation,
		&i.ScoredAt,
	)
	return i, err
}
