// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package models

import (
	"context"
	"database/sql"
)

const countIPOsWithNonZeroSubscriptions = `-- name: CountIPOsWithNonZeroSubscriptions :one
SELECT COUNT(*) FROM (
    SELECT ipo_id
    FROM subscription_data
    WHERE times_subscribed IS NOT NULL AND times_subscribed > 0
    GROUP BY ipo_id
    HAVING COUNT(DISTINCT category) >= 4
) AS sub
`

func (q *Queries) CountIPOsWithNonZeroSubscriptions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIPOsWithNonZeroSubscriptions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubscriptionData = `-- name: CreateSubscriptionData :one
INSERT INTO subscription_data (
    ipo_id,
    category,
    times_subscribed
) VALUES (
    $1, $2, $3
)
RETURNING id, ipo_id, category, times_subscribed, recorded_at
`

type CreateSubscriptionDataParams struct {
	IpoID           int64
	Category        string
	TimesSubscribed sql.NullString
}

func (q *Queries) CreateSubscriptionData(ctx context.Context, arg CreateSubscriptionDataParams) (SubscriptionDatum, error) {
	row := q.db.QueryRowContext(ctx, createSubscriptionData, arg.IpoID, arg.Category, arg.TimesSubscribed)
	var i SubscriptionDatum
	err := row.Scan(
		&i.ID,
		&i.IpoID,
		&i.Category,
		&i.TimesSubscribed,
		&i.RecordedAt,
	)
	return i, err
}

const getLatestSubscription = `-- name: GetLatestSubscription :many
SELECT DISTINCT ON (category) id, ipo_id, category, times_subscribed, recorded_at
FROM subscription_data
WHERE ipo_id = $1
ORDER BY category, recorded_at DESC
`

// Gets the latest entry for each category for a given IPO.
func (q *Queries) GetLatestSubscription(ctx context.Context, ipoID int64) ([]SubscriptionDatum, error) {
	rows, err := q.db.QueryContext(ctx, getLatestSubscription, ipoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubscriptionDatum
	for rows.Next() {
		var i SubscriptionDatum
		if err := rows.Scan(
			&i.ID,
			&i.IpoID,
			&i.Category,
			&i.TimesSubscribed,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
