// Code generated by sqlc. DO NOT EDIT.
// source: valuation.sql

package models

import (
	"context"
	"database/sql"
)

const createOrUpdateValuation = `-- name: CreateOrUpdateValuation :one
INSERT INTO valuation (
    ipo_id,
    issue_price,
    market_cap,
    pe_ratio,
    pb_ratio,
    ev_ebitda
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (ipo_id) DO UPDATE 
SET issue_price = EXCLUDED.issue_price,
    market_cap = EXCLUDED.market_cap,
    pe_ratio = EXCLUDED.pe_ratio,
    pb_ratio = EXCLUDED.pb_ratio,
    ev_ebitda = EXCLUDED.ev_ebitda
RETURNING id, ipo_id, issue_price, market_cap, pe_ratio, pb_ratio, ev_ebitda
`

type CreateOrUpdateValuationParams struct {
	IpoID      int64
	IssuePrice sql.NullString
	MarketCap  sql.NullString
	PeRatio    sql.NullString
	PbRatio    sql.NullString
	EvEbitda   sql.NullString
}

func (q *Queries) CreateOrUpdateValuation(ctx context.Context, arg CreateOrUpdateValuationParams) (Valuation, error) {
	row := q.db.QueryRowContext(ctx, createOrUpdateValuation,
		arg.IpoID,
		arg.IssuePrice,
		arg.MarketCap,
		arg.PeRatio,
		arg.PbRatio,
		arg.EvEbitda,
	)
	var i Valuation
	err := row.Scan(
		&i.ID,
		&i.IpoID,
		&i.IssuePrice,
		&i.MarketCap,
		&i.PeRatio,
		&i.PbRatio,
		&i.EvEbitda,
	)
	return i, err
}

const getValuationByIPO = `-- name: GetValuationByIPO :one
SELECT id, ipo_id, issue_price, market_cap, pe_ratio, pb_ratio, ev_ebitda FROM valuation
WHERE ipo_id = $1 LIMIT 1
`

func (q *Queries) GetValuationByIPO(ctx context.Context, ipoID int64) (Valuation, error) {
	row := q.db.QueryRowContext(ctx, getValuationByIPO, ipoID)
	var i Valuation
	err := row.Scan(
		&i.ID,
		&i.IpoID,
		&i.IssuePrice,
		&i.MarketCap,
		&i.PeRatio,
		&i.PbRatio,
		&i.EvEbitda,
	)
	return i, err
}
